name: s3cache
description: Upload and download artifacts
author: https://github.com/buildkite
requirements: []
configuration:
  properties:
    directories:
      type: [string, array]
    bucket:
      type: string
  required:
    - directories
    - bucket
  additionalProperties: false
