#!/bin/bash
set -euo pipefail

if [[ "${BUILDKITE_PLUGIN_S3_CACHE_DEBUG:-false}" =~ (true|on|1) ]]; then
  echo "--- :hammer: Enabling debug mode"
  set -x
fi

paths=()

if [[ -n "${BUILDKITE_PLUGIN_S3_CACHE_DIRECTORIES:-}" ]]; then
  paths+=("$BUILDKITE_PLUGIN_S3_CACHE_DIRECTORIES")
fi

while IFS='=' read -r path _; do
  if [[ $path =~ ^(BUILDKITE_PLUGIN_S3_CACHE_DIRECTORIES_[0-9]+) ]]; then
    paths+=("${!path}")
  fi
done < <(env | sort)

if [ "${#paths[@]}" -gt 0 ]; then
  echo "--- Compressing cache with tar"

  # Check if folders exist
  present_paths=$(ls -d ${paths[*]} 2>/dev/null)
  if [[ -n "${present_paths}" ]]; then
    tar vzcf "./cache.tar.gz" $present_paths
  else
    echo "No paths found for: "
    echo "${paths[*]}"
  fi

  if [[ -e "./cache.tar.gz" ]]; then
    echo "--- Uploading cache to ${BUILDKITE_PLUGIN_S3_CACHE_BUCKET}"
    aws s3 cp \
      "./cache.tar.gz" \
      "s3://${BUILDKITE_PLUGIN_S3_CACHE_BUCKET}/${BUILDKITE_PIPELINE_SLUG}/${BUILDKITE_BRANCH}.tar.gz"
  else
    echo "File: cache.tar.gz nothing to upload"
  fi
fi
