#!/bin/bash
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# shellcheck source=lib/params.bash
. "$DIR/../lib/params.bash"

if [[ "${BUILDKITE_PLUGIN_S3_CACHE_DEBUG:-false}" =~ (true|on|1) ]]; then
  echo "--- :hammer: Enabling debug mode"
  set -x
fi

FILENAME=$(echo "${BUILDKITE_LABEL:-"no label"}" | sha256sum | cut -d" " -f 1)

mapfile -t paths < <(plugin_read_list DIRECTORIES)

if [ ${#paths[@]} -gt 0 ]; then
  echo "--- Compressing cache with tar"
  # Filter existing paths
  shopt -s extglob
  shopt -s nullglob
  tarlist=()
  for path in ${paths[@]}; do
    if [[ -e "$path" ]]; then
      tarlist+=("$path")
    fi
  done

  if [[ "${#tarlist[@]}" -gt 0 ]]; then
    tar vzcf "./cache.tar.gz" ${tarlist[@]}

    if [[ -e "./cache.tar.gz" ]]; then
      echo "--- Uploading cache to ${BUILDKITE_PLUGIN_S3_CACHE_BUCKET}"
      aws s3 cp \
        "./cache.tar.gz" \
        "s3://${BUILDKITE_PLUGIN_S3_CACHE_BUCKET}/${BUILDKITE_PIPELINE_SLUG}/${BUILDKITE_BRANCH}/${FILENAME}.tar.gz"
    else
      echo "File cache.tar.gz missing, nothing to upload"
    fi

  else
    echo "No files found for: "
    echo "${paths[*]}"
  fi
fi
